# Generated by Django 4.0.6 on 2024-08-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
    ]
